# File: docusign/1fe-widget-starter-kit/.github/workflows/widget-ci.yml
name: Widget Starter Kit CI

on:
  push:
    branches:
      - main # Or your primary development branch
  pull_request:
    branches:
      - main # Or your primary development branch
  workflow_dispatch: # Allows manual triggering from the Actions tab
    inputs:
      node_version_override:
        description: 'Override Node.js version for this run (e.g., 20)'
        required: false
        type: string

jobs:
  run_minimal_ci:
    name: Run Minimal CI
    # This line calls the reusable workflow from your 1fe-ci-cd repository.
    # It's crucial to use a specific tag or commit SHA for stability in production.
    # For testing, you can use @main, but update it before relying on it heavily.
    uses: docusign/1fe-ci-cd/.github/workflows/ci-widgets.yml@main # Replace @main with e.g. @v1.0.0 when ready

    with:
      # Pass the Node.js version.
      # If manually triggered and node_version_override is provided, use that. Otherwise, default to '18'.
      node-version: ${{ github.event.inputs.node_version_override || '18' }}

    # secrets: inherit # Not needed for this minimal example, but good to remember for later when you add steps requiring secret