name: Widget CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      node_version_override:
        description: "Override Node.js version for this run (e.g., 20)"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  id-token: write

jobs:
  run_minimal_ci:
    name: Widget CI
    uses: docusign/1fe-ci-cd/.github/workflows/ci-widgets.yml@fix/commit-author-bypass
    with:
      node-version: ${{ github.event.inputs.node_version_override || '22' }}
    secrets:
      AKAMAI_NS_SSH_PRIVATE_KEY: ${{ secrets.AKAMAI_NS_SSH_PRIVATE_KEY }}
      AZURE_APP_CONFIG_CONNECTION_STRING: ${{ secrets.AZURE_APP_CONFIG_CONNECTION_STRING }}
      PRIVATE_KEY_1FE_ADMIN_GITHUB_APP: ${{ secrets.PRIVATE_KEY_1FE_ADMIN_GITHUB_APP }}
