# FILE: docusign/1fe-widget-starter-kit/.github/workflows/widget-ci.yml
name: Widget Starter Kit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      node_version_override:
        description: 'Override Node.js version for this run (e.g., 20)'
        required: false
        type: string

jobs:
  run_minimal_ci:
    name: Run Minimal CI
    uses: docusign/1fe-ci-cd/.github/workflows/ci-widgets.yml@main
    with:
      node-version: ${{ github.event.inputs.node_version_override || '22' }}
    secrets:
      PRIVATE_KEY_FOR_1FE: ${{ secrets.SSH_PRIVATE_1FE }}
      PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG: ${{ secrets.SSH_PRIVATE_BASE_CONFIG }}
      AKAMAI_NS_SSH_PRIVATE_KEY: ${{ secrets.AKAMAI_NS_SSH_PRIVATE_KEY }}
      AZURE_APP_CONFIG_CONNECTION_STRING: ${{ secrets.AZURE_APP_CONFIG_CONNECTION_STRING }}